package main

// * -----------------------------------------------------------
// *
// * Auto-Generated by gson-api-generator on 2015-12-09 00:28:46.336925093 -0400 EDT
// *
// * Command Line Args
// * ./gson-api-generator -action=new -goPath=github.com/mccraymt/ms-crypto -dbType=orchestrate
// *
// * -----------------------------------------------------------

import (
	"strconv"

	log "github.com/Sirupsen/logrus"
	cfg "github.com/mccraymt/ms-crypto/config"
	web "github.com/mccraymt/ms-crypto/web_server"
)

func main() {
	log.WithFields(log.Fields{
		"e":    "webserver_start",
		"port": cfg.Config.Port,
	}).Info(".")

	// start webserver
	server := web.NewServer()
	server.RunOnAddr(":" + strconv.Itoa(cfg.Config.Port))
}
